name: WakaTime Readme Metrics

on:
  workflow_dispatch: # Allows manual triggering
  schedule:
    - cron: "0 */2 * * *" # Runs every 2 hours

jobs:
  update-readme:
    name: Update WakaTime Stats in README
    runs-on: ubuntu-latest

    steps:
      - name: Update WakaTime stats
        uses: athul/waka-readme@v0.3.1 # Keep using this pinned version
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }} # Required

          # --- Meta Config ---
          REPOSITORY: Anushlinux/Anushlinux
          API_BASE_URL: https://wakatime.com/api

          # --- Display Config ---
          SHOW_TITLE: true
          SECTION_NAME: waka
          BLOCKS: ->
          # CODE_LANG: rust # Commented: Setting this restricts the visual output unnecessarily
          TIME_RANGE: all_time
          LANG_COUNT: 10
          SHOW_TIME: true
          SHOW_TOTAL: true
          SHOW_MASKED_TIME: false
          STOP_AT_OTHER: true
          IGNORED_LANGUAGES: YAML JSON TOML

          # --- Commit Config ---
          COMMIT_MESSAGE: "chore: update WakaTime stats in README"
          TARGET_BRANCH: master
          TARGET_PATH: README.md
          COMMITTER_NAME: GitHubActionBot
          COMMITTER_EMAIL: action-bot@github.com
          AUTHOR_NAME: Anushrut
          AUTHOR_EMAIL: anushrut.p@somaiya.edu
